command /give::nuclearsystemsk:
    trigger:
        if sender is op:
            give 1 obsidian named "&f[&6Nuclear&f] &6원자로" with lore "&f[&7-&f] 설치 후 우클릭 하여 열 수 있습니다." to player


on place of obsidian:
    if name of player's tool is "&f[&6Nuclear&f] &6원자로":
        set {Nuclear::Nuclear::%location of event-block%::location} to location of event-block
        set {Nuclear::Nuclear::%location of event-block%::temp} to 25
        set {Nuclear::Nuclear::%location of event-block%::coal} to 0
        set {Nuclear::Nuclear::%location of event-block%::uranium} to 0
        set {Nuclear::Nuclear::%location of event-block%::airpress} to 0
        set {Nuclear::Nuclear::%location of event-block%::status} to false
        send "&f[&aNUCLEAR&f] 원자로가 설치되었습니다!" to sender


on break of obsidian:
    if {Nuclear::Nuclear::%location of event-block%::location} is location of event-block:
        send "&f[&aNUCLEAR&f] 원자로가 제거되었습니다!" to sender
        delete {Nuclear::Nuclear::%location of event-block%::*}

on right click on obsidian:
    if {Nuclear::Nuclear::%location of event-block%::location} is location of event-block:
        open chest with 6 rows named "&f[&aNUCLEAR&f] 원자로" to player
        set {_n} to 0
        loop 54 times:
            set slot {_n} of current inventory of player to black stained glass pane
            add 1 to {_n}
        set {_n} to 10
        loop 7 times:
            set slot {_n} of current inventory of player to glass pane named "&e[ &6제어봉 뚜껑 마개 &e]" with lore "&f[&7-&f] 클릭하여 제어봉 뚜껑을 열고, 우라늄을 넣으세요!"
            add 1 to {_n}
        while name of player's current inventory contains "&f[&aNUCLEAR&f] 원자로":
            set slot 21 of current inventory of player to iron bar named "&6석탄을 넣으세요! ->"
            set slot 22 of current inventory of player to air
            set slot 23 of current inventory of player to iron bar named "&6<- 석탄을 넣으세요!"
            set slot 31 of current inventory of player to clock named "&f원자로 온도: &c%{Nuclear::Nuclear::%location of event-block%::temp}%&f℃"
            wait 1 tick


on inventory click:
    if inventory name contains "&f[&aNUCLEAR&f] 원자로":
        if event-slot is black stained glass pane or iron bar or clock:
            cancel event
        else if event-slot is glass pane:
            cancel event
            set slot index of event-slot of current inventory of player to air

on break of coal ore or deepslate coal ore:
    chance of 5%:
        drop 1 of scute of infinity 1 named "&a우라늄 &b238" with lore "&f[&7-&f] 원자로에 정제 후 이용 가능"
    chance of 1%:
        drop 1 of slime ball of infinity 1 named "&a우라늄 &b235" with lore "&f[&7-&f] 원자로에 이용 가능"
