options:
    prefix : &f[&6&lJELO&f]

on join:
    set {IP::%uuid of player%} to player's ip


on load:
    loop all players:
        if {IP::%uuid of loop-player%} is not set:
            set {IP::%uuid of loop-player%} to loop-player's ip


command /ip [<offlineplayer>]:
    trigger:
        if sender is op:
            if {IP::%uuid of arg-1%} is set:
                send "&f[&cIP&f] 해당 플레이어의 IP 는 &b%{IP::%uuid of arg-1%}%&f 입니다." to sender
            else:
                send "&c해당 플레이어는 데이터가 없습니다!" to sender
        else if sender is console:
            if {IP::%uuid of arg-1%} is set:
                send "&f[&cIP&f] 해당 플레이어의 IP 는 &b%{IP::%uuid of arg-1%}%&f 입니다." to sender
            else:
                send "&c해당 플레이어는 데이터가 없습니다!" to sender


command /rawjelo [<text>]:
    trigger:
        if sender is op:
            broadcast "&f[&6&lJELO&f] %colored arg-1%"
        else if sender is console:
            broadcast "&f[&6&lJELO&f] %colored arg-1%"


command /findjelo [<offlineplayer>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>] [<text>]:
    trigger:
        if sender is op:
            set {_permission} to 4
        else if sender is console:
            set {_permission} to 4

        if {_permission} is 4:
            if arg-1 is not set:
                send "{@prefix} &cCant Found Cheating player." to sender
            else if arg-2 is not set:
                send "{@prefix} &cCant Found Cheat mods." to sender
            else if arg-3 is not set:
                send "{@prefix} &cCant Found Cheat mods level" to sender
            else:
                set {_argment::1} to arg-1
                set {_argment::2} to arg-2
                set {_argment::3} to arg-3
                set {_argment::4} to arg-4
                set {_argment::5} to arg-5
                set {_argment::6} to arg-6
                set {_argment::7} to arg-7
                set {_argment::8} to arg-8
                set {_argment::9} to arg-9
                set {_argment::10} to arg-10
                set {_argment::11} to arg-11
                set {_argment::12} to arg-12
                set {_argment::13} to arg-13
                set {_argment::14} to arg-14
                set {_argment::15} to arg-15

                set {_viewcheat} to "&c"
                set {_n} to 2
                loop 7 times:
                    if {_argment::%{_n}%} is set:
                        if {_argment::%{_n}+1%} is not set:
                            set {_argment::%{_n}+1%} to "&8NaN&7"
                        if {_n} is 2:
                            set {_viewcheat} to "&c%{_argment::%{_n}%}%&7[Lv:%{_argment::%{_n}+1%}%]"
                        else:
                            set {_viewcheat} to "%{_viewcheat}%&7, &c%{_argment::%{_n}%}%&7[Lv:%{_argment::%{_n}+1%}%]"
                        add 2 to {_n}
                    else:
                        stop loop
                broadcast "{@prefix} &b%arg-1% &f님께서 &c%{_viewcheat}% &f사용이 의심됩니다."


            

on tab complete of "/findjelo":
    set tab completions for position 1 to all players

    #  CHEAT NAME
    set tab completions for position 2 to "KillAura", "MultiAura", "Speed", "Flight", "Creative-Fly", "BunnyHop", "AutoClicker", "Reach", "XRay", "SeedCracker", "Jesus", "ESP", "Dolphin", "Blink", "Timer", "Spammer", "AutoFish", "AutoJump", "AutoSteal", "InvWalk", "Jetpack", "FastBreak", "FastPlace", "BoatFly", "FreeCam", "Sneak", "Nuker", "Spider", "FastLadder", "AutoSign", "TriggerBot", "Baritone", "AutoBuild", "Criticals", ".Damage", "FakeChat" and "Finder"
    set tab completions for position 4 to "KillAura", "MultiAura", "Speed", "Flight", "Creative-Fly", "BunnyHop", "AutoClicker", "Reach", "XRay", "SeedCracker", "Jesus", "ESP", "Dolphin", "Blink", "Timer", "Spammer", "AutoFish", "AutoJump", "AutoSteal", "InvWalk", "Jetpack", "FastBreak", "FastPlace", "BoatFly", "FreeCam", "Sneak", "Nuker", "Spider", "FastLadder", "AutoSign", "TriggerBot", "Baritone", "AutoBuild", "Criticals", ".Damage", "FakeChat" and "Finder"
    set tab completions for position 6 to "KillAura", "MultiAura", "Speed", "Flight", "Creative-Fly", "BunnyHop", "AutoClicker", "Reach", "XRay", "SeedCracker", "Jesus", "ESP", "Dolphin", "Blink", "Timer", "Spammer", "AutoFish", "AutoJump", "AutoSteal", "InvWalk", "Jetpack", "FastBreak", "FastPlace", "BoatFly", "FreeCam", "Sneak", "Nuker", "Spider", "FastLadder", "AutoSign", "TriggerBot", "Baritone", "AutoBuild", "Criticals", ".Damage", "FakeChat" and "Finder"
    set tab completions for position 8 to "KillAura", "MultiAura", "Speed", "Flight", "Creative-Fly", "BunnyHop", "AutoClicker", "Reach", "XRay", "SeedCracker", "Jesus", "ESP", "Dolphin", "Blink", "Timer", "Spammer", "AutoFish", "AutoJump", "AutoSteal", "InvWalk", "Jetpack", "FastBreak", "FastPlace", "BoatFly", "FreeCam", "Sneak", "Nuker", "Spider", "FastLadder", "AutoSign", "TriggerBot", "Baritone", "AutoBuild", "Criticals", ".Damage", "FakeChat" and "Finder"
    set tab completions for position 10 to "KillAura", "MultiAura", "Speed", "Flight", "Creative-Fly", "BunnyHop", "AutoClicker", "Reach", "XRay", "SeedCracker", "Jesus", "ESP", "Dolphin", "Blink", "Timer", "Spammer", "AutoFish", "AutoJump", "AutoSteal", "InvWalk", "Jetpack", "FastBreak", "FastPlace", "BoatFly", "FreeCam", "Sneak", "Nuker", "Spider", "FastLadder", "AutoSign", "TriggerBot", "Baritone", "AutoBuild", "Criticals", ".Damage", "FakeChat" and "Finder"
    set tab completions for position 12 to "KillAura", "MultiAura", "Speed", "Flight", "Creative-Fly", "BunnyHop", "AutoClicker", "Reach", "XRay", "SeedCracker", "Jesus", "ESP", "Dolphin", "Blink", "Timer", "Spammer", "AutoFish", "AutoJump", "AutoSteal", "InvWalk", "Jetpack", "FastBreak", "FastPlace", "BoatFly", "FreeCam", "Sneak", "Nuker", "Spider", "FastLadder", "AutoSign", "TriggerBot", "Baritone", "AutoBuild", "Criticals", ".Damage", "FakeChat" and "Finder"
    set tab completions for position 14 to "KillAura", "MultiAura", "Speed", "Flight", "Creative-Fly", "BunnyHop", "AutoClicker", "Reach", "XRay", "SeedCracker", "Jesus", "ESP", "Dolphin", "Blink", "Timer", "Spammer", "AutoFish", "AutoJump", "AutoSteal", "InvWalk", "Jetpack", "FastBreak", "FastPlace", "BoatFly", "FreeCam", "Sneak", "Nuker", "Spider", "FastLadder", "AutoSign", "TriggerBot", "Baritone", "AutoBuild", "Criticals", ".Damage", "FakeChat" and "Finder"
    
    # CHEAT LEVEL
    set tab completions for position 3 to "1", "2", "3", "4", "5", "6", "7", "8", "9" and "MAX"
    set tab completions for position 5 to "1", "2", "3", "4", "5", "6", "7", "8", "9" and "MAX"
    set tab completions for position 7 to "1", "2", "3", "4", "5", "6", "7", "8", "9" and "MAX"
    set tab completions for position 9 to "1", "2", "3", "4", "5", "6", "7", "8", "9" and "MAX"
    set tab completions for position 11 to "1", "2", "3", "4", "5", "6", "7", "8", "9" and "MAX"
    set tab completions for position 13 to "1", "2", "3", "4", "5", "6", "7", "8", "9" and "MAX"
    set tab completions for position 15 to "1", "2", "3", "4", "5", "6", "7", "8", "9" and "MAX"
